#theme: minima
title: shijiang.tk
email: ssj1595329871@qq.com
description: >-
  This is my markdown notes.
baseurl: ""
url: ""
github_username: sunshijiang

remote_theme: pages-themes/cayman #jeeekyll-theme-cayman
plugins:
  - jekyll-remote-theme #feed
#theme: minima
#plugins:
#  - jekyll-feed

