#theme: minima
title: shijiang.tk
email: ssj1595329871@qq.com
description: >-
  This is my markdown notes.
baseurl: ""
url: ""
github_username: sunshijiang

remote_theme: pages-themes/cayman #jeeekyll-theme-cayman
#theme: cayman
plugins:
  - jekyll-remote-theme #feed
  - jekyll-relative-links
relative-links:
  enabled: true
  collections: true



#theme: minima
#plugins:
#  - jekyll-feed

#show_downloads: true
#github.is_project_page: true

